# Generated by Django 4.2.3 on 2024-03-07 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('ubicacion', models.URLField(blank=True, null=True, verbose_name='Ubicación maps')),
                ('telefono', models.CharField(blank=True, max_length=80, null=True, verbose_name='Número de teléfono')),
                ('telefono_urgencia', models.CharField(blank=True, max_length=80, null=True, verbose_name='Teléfono urgencia')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200, verbose_name='Tipo de estudio')),
                ('consultorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_estudios', to='consultorio.consultorio')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre y apellido')),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=12)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('nro_telefono', models.CharField(blank=True, max_length=80, null=True, verbose_name='Número de teléfono')),
                ('nro_documento', models.CharField(blank=True, max_length=80, null=True, verbose_name='Número de documento')),
                ('consultorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='consultorio.consultorio')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre laboratorio')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=80, null=True, verbose_name='Número de teléfono')),
                ('doctor_encargado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre encargado')),
                ('consultorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laboratorios', to='consultorio.consultorio')),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha estudio')),
                ('proxima_consulta', models.DateTimeField(blank=True, null=True)),
                ('notificado', models.BooleanField(default=False)),
                ('resultado', models.FileField(blank=True, null=True, upload_to='')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_creados', to=settings.AUTH_USER_MODEL)),
                ('laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios', to='consultorio.laboratorio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='consultorio.paciente')),
                ('tipo_estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudios', to='consultorio.tipoestudio')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('proxima_consulta', models.DateTimeField(blank=True, null=True, verbose_name='Próxima consulta')),
                ('receta', models.TextField(blank=True, null=True, verbose_name='Receta')),
                ('receta_foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Receta Foto')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_creados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='consultorio.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='consultorio.consulta')),
            ],
        ),
    ]
