services:
  nginx:
    container_name: nginx_virtualclinic
    restart: on-failure
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_virtualclinic_volume:/app/static
      - media_virtualclinic_volume:/app/media
    ports:
      - 9001:9001
    depends_on:
      - web
  web:
    container_name: virtualclinic_app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    env_file:
      - current.env
    command: sh -c "gunicorn virtualclinic.wsgi:application --bind 0.0.0.0:5001"
    volumes:
      - static_virtualclinic_volume:/app/static
      - media_virtualclinic_volume:/app/media
      - db_virtualclinic_volume:/app/data/

volumes:
  static_virtualclinic_volume:
  media_virtualclinic_volume:
  db_virtualclinic_volume: