# Generated by Django 4.2.11 on 2024-03-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('nutricion', 'Nutrición'), ('psicologia', 'Psicología'), ('odontologia', 'Odontología'), ('psiquiatria', 'Psiquiatría'), ('dematologia', 'Dermatología'), ('kinesiologia', 'Kinesiología'), ('paciente', 'Paciente'), ('otro', 'Otro')], max_length=30),
        ),
    ]
